### ISSUE TITLE
Docs website

### ISSUE THREAD

**Issue by darribas** [conjuring/conjuring#25]
Once we have a testable version, it'd be good to set up a documentation website (that can live as static html on a `docs` folder on `master` and served up through GH Pages). That'd make it easier for people to get a sense of what the project does and how to get started.

---
@casperdcl EDIT:

currently official documentation is in [README.md](https://github.com/casperdcl/conjuring/blob/master/README.md,) but parts of https://github.com/casperdcl/conjuring/wiki/Install-Intel-NUC8i7BEH could be mostly movable to the README.md file, or the proposed docs website

**Comment by casperdcl** [comment]
closed by https://github.com/conjuring/conjuring.github.io
